# Frontend Dockerfile
FROM node:20

# Set working directory
WORKDIR /app

# Copy only package files first (caching dependencies)
COPY package*.json yarn.lock ./

# Install dependencies inside container
RUN yarn install --frozen-lockfile

# Copy the rest of the source code
COPY . .

# Environment for dev
ENV ESLINT_NO_DEV_ERRORS=true

# Expose dev port
EXPOSE 3000

# Start dev server
CMD ["yarn", "dev"]
