import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full h-24 bg-white shadow-md flex items-center justify-center">
          <div className="flex items-center justify-center h-full max-w-lg mx-auto">
            <p className="font-montserrat text-[24px] font-bold text-green-teal">SWStarter</p>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
